import = [ "~/.config/alacritty/system.toml" ]

[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "ReceiveChar" },
    { key = "P", mods = "Control|Shift", action = "ReceiveChar" },
]

[window]
padding = { x = 7, y = 7 }

[font]
size = 13.0
normal = { family = "Noto Sans Mono", style = "Regular" }
bold = { style = "Bold" }

# Colors (Gruvbox dark)
[colors.primary]
background = '0x282828'
foreground = '0xebdbb2'

[colors.cursor]
cursor = '0xebdbb2'
text = '0x282828'

[colors.normal]
black = '0x282828'
red = '0xcc241d'
green = '0x98971a'
yellow = '0xd79921'
blue = '0x458588'
magenta = '0xb16286'
cyan = '0x689d6a'
white = '0xa89984'

[colors.bright]
black = '0x928374'
red = '0xfb4934'
green = '0xb8bb26'
yellow = '0xfabd2f'
blue = '0x83a598'
magenta = '0xd3869b'
cyan = '0x8ec07c'
white = '0xebdbb2'

