shell = "ubuntu2204.exe"

[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "ReceiveChar" },
    { key = "P", mods = "Control|Shift", action = "ReceiveChar" },
]

[window]
padding = { x = 7, y = 7 }

[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Medium"}
size = 13.0

# TokyoNight Alacritty Colors
[colors.primary]
background = '#222436'
foreground = '#c8d3f5'

[colors.cursor]
cursor = '#c8d3f5'
text = '#222436'

[colors.normal]
black = '#1b1d2b'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#828bb8'

[colors.bright]
black = '#444a73'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#c8d3f5'

[[colors.indexed_colors]]
index = 16
color = '#ff966c'

[[colors.indexed_colors]]
index = 17
color = '#c53b53'
