add_newline = false
format = """\
$cmd_duration\
$battery\
$username@$hostname:$directory$git_branch$git_commit$git_state$character"""

palette = 'gruvbox_dark'

[directory]
truncation_length = 10
truncation_symbol = '…/'

[username]
show_always = true
style_user = 'green'
format = '[$user]($style)'

[hostname]
ssh_only = false
style = 'purple'
format = '[$ssh_symbol$hostname]($style)'

[cmd_duration]
min_time = 20_000
format = """took [$duration]($style)

"""

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

